DROP DATABASE IF EXISTS planeacion_y_evaluacion;
CREATE DATABASE planeacion_y_evaluacion;
USE planeacion_y_evaluacion;

DROP TABLE IF EXISTS titulares;
CREATE TABLE titulares(
    id_titular INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL, 
    apellidos VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    id_area VARCHAR(3),
    id_registrante INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_dependencia INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS titulares_eliminados;
CREATE TABLE titulares_eliminados(
    id_titular_eliminado INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL, 
    apellidos VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    id_area INT,
    id_registrante INT,
    id_eliminante INT,
    fecha_alta DATETIME ,
    fecha_eliminacion DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_dependencia INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS dependencias_generales;
CREATE TABLE dependencias_generales(
    id_dependencia INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    clave_dependencia VARCHAR(15) NOT NULL,
    nombre_dependencia_general VARCHAR(255) NOT NULL,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    tipo VARCHAR(10),
    anio VARCHAR(4)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO dependencias_generales (clave_dependencia, nombre_dependencia_general,tipo,anio) VALUES 
("A00","PRESIDENCIA","Municipios","2023"),
("A01","Comunicación Social","Municipios","2023"),
("A02","Derechos Humanos","Municipios","2023"),
("B00","SINDICATURAS","Municipios","2023"),
("B01","Sindicatura I","Municipios","2023"),
("B02","Sindicatura II","Municipios","2023"),
("C00","REGIDURIAS","Municipios","2023"),
("C01","Regiduría I","Municipios","2023"),
("C02","Regiduría II","Municipios","2023"),
("C03","Regiduría III","Municipios","2023"),
("C04","Regiduría IV","Municipios","2023"),
("C05","Regiduría V","Municipios","2023"),
("C06","Regiduría VI","Municipios","2023"),
("C07","Regiduría VII","Municipios","2023"),
("C08","Regiduría VIII","Municipios","2023"),
("C09","Regiduría IX","Municipios","2023"),
("C10","Regiduría X","Municipios","2023"),
("C11","Regiduría XI","Municipios","2023"),
("C12","Regiduría XII","Municipios","2023"),
("D00","SECRETARÍA DEL AYUNTAMIENTO","Municipios","2023"),
("E00","ADMINISTRACIÓN","Municipios","2023"),
("E01","Planeación","Municipios","2023"),
("E02","Informática","Municipios","2023"),
("E03","Eventos Especiales","Municipios","2023"),
("F00","DESARROLLO URBANO Y OBRAS PÚBLICAS","Municipios","2023"),
("F01","Desarrollo Urbano y Servicios Públicos","Municipios","2023"),
("G00","ECOLOGÍA","Municipios","2023"),
("H00","SERVICIOS PÚBLICOS","Municipios","2023"),
("H01","AGUA POTABLE","Municipios","2023"),
("I00","PROMOCIÓN SOCIAL","Municipios","2023"),
("I01","Desarrollo Social","Municipios","2023"),
("I02","Salud","Municipios","2023"),
("J00","GOBIERNO MUNICIPAL","Municipios","2023"),
("K00","CONTRALORÍA","Municipios","2023"),
("L00","TESORERÍA","Municipios","2023"),
("M00","CONSEJERÍA JURÍDICA","Municipios","2023"),
("N00","DIRECCIÓN DE DESARROLLO ECONÓMICO","Municipios","2023"),
("N01","Desarrollo Agropecuario","Municipios","2023"),
("O00","EDUCACIÓN CULTURAL Y BIENESTAR SOCIAL","Municipios","2023"),
("P00","ATENCIÓN CIUDADANA","Municipios","2023"),
("Q00","SEGURIDAD PÚBLICA Y TRÁNSITO","Municipios","2023"),
("R00","CASA DE LA CULTURA","Municipios","2023"),
("S00","UNIDAD DE INFORMACIÓN, PLANEACIÓN, PROGRAMACIÓN Y EVALUACIÓN","Municipios","2023"),
("T00","PROTECCIÓN CIVIL","Municipios","2023"),
("U00","TURISMO","Municipios","2023"),
("V00","DIRECCIÓN DE LAS MUJERES","Municipios","2023");

INSERT INTO dependencias_generales (clave_dependencia, nombre_dependencia_general,tipo,anio) VALUES 
("A00","DIRECCIÓN GENERAL","Organismos Operadores de Agua","2023"),
("A01","Subdirección General","Organismos Operadores de Agua","2023"),
("A04","Control de Gestión","Organismos Operadores de Agua","2023"),
("A05","Unidad de Informática","Organismos Operadores de Agua","2023"),
("B00","FINANZAS Y ADMINISTRACIÓN","Organismos Operadores de Agua","2023"),
("B01","Finanzas","Organismos Operadores de Agua","2023"),
("B02","Administración","Organismos Operadores de Agua","2023"),
("B03","Comercialización","Organismos Operadores de Agua","2023"),
("C00","UNIDAD TECNICA DE OPERACIÓN","Organismos Operadores de Agua","2023"),
("C01","Construcción","Organismos Operadores de Agua","2023"),
("C02","Operación","Organismos Operadores de Agua","2023"),
("C03","Mantenimiento","Organismos Operadores de Agua","2023"),
("D00","UNIDAD JURÍDICA","Organismos Operadores de Agua","2023"),
("E00","UNIDAD DE PLANEACIÓN","Organismos Operadores de Agua","2023"),
("E01","Planeación","Organismos Operadores de Agua","2023"),
("E02","Estudios y Proyectos","Organismos Operadores de Agua","2023"),
("G00","CONTRALORÍA INTERNA","Organismos Operadores de Agua","2023");

INSERT INTO dependencias_generales (clave_dependencia, nombre_dependencia_general,tipo,anio) VALUES 
("A00","PRESIDENCIA","Sistemas Municipales DIF","2023"),
("B00","DIRECCIÓN GENERAL","Sistemas Municipales DIF","2023"),
("C00","TESORERÍA","Sistemas Municipales DIF","2023"),
("D00","ÁREA DE ADMINISTRACIÓN","Sistemas Municipales DIF","2023"),
("E00","ÁREA DE OPERACIÓN","Sistemas Municipales DIF","2023"),
("F00","ÁREA DE GESTIÓN SOCIAL","Sistemas Municipales DIF","2023"),
("G00","CONTRALORÍA INTERNA","Sistemas Municipales DIF","2023");

INSERT INTO dependencias_generales (clave_dependencia, nombre_dependencia_general,tipo,anio) VALUES 
("A00","DIRECCIÓN GENERAL","Institutos Municipales de Cultura Física y Deporte","2023"),
("B00","ADMINISTRACIÓN Y FINANZAS","Institutos Municipales de Cultura Física y Deporte","2023"),
("C00","DIFUSIÓN Y OPERACIÓN","Institutos Municipales de Cultura Física y Deporte","2023"),
("D00","CONTRALORIA INTERNA","Institutos Municipales de Cultura Física y Deporte","2023");

INSERT INTO dependencias_generales (clave_dependencia, nombre_dependencia_general,tipo,anio) VALUES 
("A00","DIRECCIÓN GENERAL","Institutos Municipales de la Juventud","2023"),
("B00","ADMINISTRACIÓN Y FINANZAS","Institutos Municipales de la Juventud","2023"),
("C00","DIFUSIÓN Y OPERACIÓN","Institutos Municipales de la Juventud","2023"),
("D00","CONTRALORIA INTERNA","Institutos Municipales de la Juventud","2023");



DROP TABLE IF EXISTS dependencias_auxiliares;
CREATE TABLE dependencias_auxiliares(
    id_dependencia_auxiliar INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    clave_dependencia_auxiliar VARCHAR(15),
    nombre_dependencia_auxiliar VARCHAR(255),
    tipo VARCHAR(20),
    anio VARCHAR(4),
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO dependencias_auxiliares (clave_dependencia_auxiliar,nombre_dependencia_auxiliar,tipo,anio) VALUES 
("100","Secretaría Particular","Ayuntamiento","2023"),
("101","Secretaría Técnica","Ayuntamiento","2023"),
("102","Derechos Humanos","Ayuntamiento","2023"),
("103","Comunicación Social","Ayuntamiento","2023"),
("104","Seguridad Pública","Ayuntamiento","2023"),
("105","Coordinación Municipal de Protección Civil","Ayuntamiento","2023"),
("106","Cuerpo de Bomberos","Ayuntamiento","2023"),
("107","Urbanismo y Vivienda","Ayuntamiento","2023"),
("108","Oficialía Mediadora-Conciliadora","Ayuntamiento","2023"),
("109","Registro Civil","Ayuntamiento","2023"),
("110","Acción Cívica","Ayuntamiento","2023"),
("111","Coordinación de Delegaciones","Ayuntamiento","2023"),
("112","Participación Ciudadana","Ayuntamiento","2023"),
("113","Cronista Municipal","Ayuntamiento","2023"),
("114","Control Patrimonial","Ayuntamiento","2023"),
("115","Ingresos","Ayuntamiento","2023"),
("116","Egresos","Ayuntamiento","2023"),
("117","Presupuesto","Ayuntamiento","2023"),
("118","Catastro Municipal","Ayuntamiento","2023"),
("119","Contabilidad","Ayuntamiento","2023"),
("120","Administración y Desarrollo de Personal","Ayuntamiento","2023"),
("121","Recursos Materiales","Ayuntamiento","2023"),
("122","Unidad de Transparencia","Ayuntamiento","2023"),
("123","Desarrollo Urbano","Ayuntamiento","2023"),
("124","Obras Públicas","Ayuntamiento","2023"),
("125","Servicios Públicos","Ayuntamiento","2023"),
("126","Limpia","Ayuntamiento","2023"),
("127","Alumbrado Público","Ayuntamiento","2023"),
("128","Parques y Jardines","Ayuntamiento","2023"),
("129","Antirrábico","Ayuntamiento","2023"),
("130","Desarrollo Agrícola y Ganadero","Ayuntamiento","2023"),
("131","Fomento Industrial","Ayuntamiento","2023"),
("132","Desarrollo Comercial y de Servicios","Ayuntamiento","2023"),
("133","Fomento Artesanal","Ayuntamiento","2023"),
("134","Auditoría Financiera","Ayuntamiento","2023"),
("135","Auditoría de Obra","Ayuntamiento","2023"),
("136","Auditoría Administrativa","Ayuntamiento","2023"),
("137","Simplificación Administrativa","Ayuntamiento","2023"),
("138","Responsabilidad y Situación Patrimonial","Ayuntamiento","2023"),
("139","Control Social","Ayuntamiento","2023"),
("140","Servicio Municipal de Empleo","Ayuntamiento","2023"),
("141","Educación","Ayuntamiento","2023"),
("142","Deporte","Ayuntamiento","2023"),
("143","Atención a la Juventud","Ayuntamiento","2023"),
("144","Gobernación","Ayuntamiento","2023"),
("145","Panteones","Ayuntamiento","2023"),
("146","Rastro","Ayuntamiento","2023"),
("147","Mercados","Ayuntamiento","2023"),
("148","Servicio Militar Municipal","Ayuntamiento","2023"),
("149","Fomento Turístico","Ayuntamiento","2023"),
("150","Cultura","Ayuntamiento","2023"),
("151","Atención a los Pueblos Indígenas","Ayuntamiento","2023"),
("152","Atención a la Mujer","Ayuntamiento","2023"),
("153","Atención a la Salud","Ayuntamiento","2023"),
("154","Vialidad y Transporte","Ayuntamiento","2023"),
("155","Área Jurídica","Ayuntamiento","2023"),
("156","Suministro de Agua Potable","Ayuntamiento","2023"),
("157","Drenaje y Saneamiento","Ayuntamiento","2023"),
("158","Tránsito","Ayuntamiento","2023"),
("159","Secretaría Técnica de Seguridad Pública","Ayuntamiento","2023"),
("160","Prevención y Control Ambiental","Ayuntamiento","2023"),
("161","Unidad Substanciadora y Resolutora","Ayuntamiento","2023"),
("162","Unidad Investigadora","Ayuntamiento","2023"),
("163","Oficialía Mediadora","Ayuntamiento","2023"),
("164","Oficialía Calificadora","Ayuntamiento","2023"),
("165","Planeación","Ayuntamiento","2023"),
("166","Programas Sociales","Ayuntamiento","2023");

INSERT INTO dependencias_auxiliares (clave_dependencia_auxiliar,nombre_dependencia_auxiliar,tipo,anio) VALUES 
("201","Área de Sistemas","Organismos Operadores de Agua","2023"),
("202","Área de Padrones, Lecturas y Facturación","Organismos Operadores de Agua","2023"),
("203","Área de Contabilidad y Presupuesto","Organismos Operadores de Agua","2023"),
("204","Área de Tesorería","Organismos Operadores de Agua","2023"),
("205","Área de Ingresos","Organismos Operadores de Agua","2023"),
("206","Área de Presupuestos","Organismos Operadores de Agua","2023"),
("207","Área de Contabilidad","Organismos Operadores de Agua","2023"),
("208","Área de Rezago y Cobranza","Organismos Operadores de Agua","2023"),
("209","Área de Recursos Humanos","Organismos Operadores de Agua","2023"),
("210","Área de Recursos Materiales y Servicios Generales","Organismos Operadores de Agua","2023"),
("211","Área de Finanzas","Organismos Operadores de Agua","2023"),
("212","Área de Administración","Organismos Operadores de Agua","2023"),
("213","Área de Adquisiciones","Organismos Operadores de Agua","2023"),
("214","Área de Patrimonio","Organismos Operadores de Agua","2023"),
("215","Área de Atención a Usuarios","Organismos Operadores de Agua","2023"),
("216","Área de Comercialización","Organismos Operadores de Agua","2023"),
("217","Área de Líneas y Tanques","Organismos Operadores de Agua","2023"),
("218","Área de Construcción, Control y Supervisión","Organismos Operadores de Agua","2023"),
("219","Área de Agua Potable","Organismos Operadores de Agua","2023"),
("220","Área de Operación","Organismos Operadores de Agua","2023"),
("221","Área de Aguas Residuales y Plantas de Tratamiento","Organismos Operadores de Agua","2023"),
("222","Área de Drenaje y Alcantarillado","Organismos Operadores de Agua","2023"),
("223","Área de Control y Micromedición","Organismos Operadores de Agua","2023"),
("224","Área de Factibilidades","Organismos Operadores de Agua","2023"),
("225","Área de Electromecánico","Organismos Operadores de Agua","2023"),
("226","Área de Cloración y Calidad del Agua","Organismos Operadores de Agua","2023"),
("227","Área de Mantenimiento","Organismos Operadores de Agua","2023"),
("228","Área Jurídica","Organismos Operadores de Agua","2023"),
("229","Área de Aseguramiento de Calidad","Organismos Operadores de Agua","2023"),
("230","Área de Planes y Programas","Organismos Operadores de Agua","2023"),
("231","Área de Coordinación Institucional","Organismos Operadores de Agua","2023"),
("232","Área de Difusión Social","Organismos Operadores de Agua","2023"),
("233","Área de Estudios y Proyectos","Organismos Operadores de Agua","2023"),
("234","Área de Cultura del Agua","Organismos Operadores de Agua","2023");

INSERT INTO dependencias_auxiliares (clave_dependencia_auxiliar,nombre_dependencia_auxiliar,tipo,anio) VALUES 
("300","Secretaría Particular","Sistemas Municipales DIF","2023"),
("301","Unidad de Asistencia Social","Sistemas Municipales DIF","2023"),
("302","Comunicación Social","Sistemas Municipales DIF","2023"),
("303","Contraloría Interna","Sistemas Municipales DIF","2023"),
("304","Planeación","Sistemas Municipales DIF","2023"),
("305","Supervisión","Sistemas Municipales DIF","2023"),
("306","Área de Finanzas","Sistemas Municipales DIF","2023"),
("307","Área de Administración","Sistemas Municipales DIF","2023"),
("308","Área de Orientación Familiar","Sistemas Municipales DIF","2023"),
("309","Área de Servicios Educativos","Sistemas Municipales DIF","2023"),
("310","Área de Salud y Deporte","Sistemas Municipales DIF","2023"),
("311","Área de Servicios Nutricionales","Sistemas Municipales DIF","2023"),
("312","Área de Servicios Jurídicos","Sistemas Municipales DIF","2023"),
("313","Área de Desarrollo Comunitario","Sistemas Municipales DIF","2023"),
("314","Área de Asistencia a Discapacitados","Sistemas Municipales DIF","2023"),
("315","Área de Informática","Sistemas Municipales DIF","2023");

INSERT INTO dependencias_auxiliares (clave_dependencia_auxiliar,nombre_dependencia_auxiliar,tipo,anio) VALUES 
("401","Área de Dirección y Coordinación","Institutos Municipales de Cultura Física ey Deporte","2023"),
("402","Área de Administración y Finanzas","Institutos Municipales de Cultura Física y Deporte","2023"),
("403","Área de Cultura Física","Institutos Municipales de Cultura Física y Deporte","2023"),
("404","Área de Deporte Social","Institutos Municipales de Cultura Física y Deporte","2023"),
("405","Área de Deporte Competitivo","Institutos Municipales de Cultura Física y Deporte","2023");

INSERT INTO dependencias_auxiliares (clave_dependencia_auxiliar,nombre_dependencia_auxiliar,tipo,anio) VALUES 
("601","Área de Dirección y Coordinación","Institutos Municipales de la Juventud","2023"),
("603","Área de Atención Juvenil","Institutos Municipales de la Juventud","2023"),
("602","Área de Administración y Finanzas","Institutos Municipales de la Juventud","2023"),
("604","Contraloría Interna","Institutos Municipales de la Juventud","2023");


DROP TABLE IF EXISTS programas_presupuestarios;
CREATE TABLE programas_presupuestarios(
    id_programa INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    codigo_programa VARCHAR(12) NOT NULL,
    nombre_programa VARCHAR(255) NOT NULL,
    objetivo_pp TEXT, -- Objetivo o resumen narrativo
    dependencia_general_gaceta VARCHAR(255), -- El que aparece en la gaceta
    pilar_o_eje VARCHAR(255), -- Transcripcion de la gaceta
    tema_desarrollo VARCHAR(255),
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    anio VARCHAR(4)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS proyectos;
CREATE TABLE proyectos(
    id_proyecto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    codigo_proyecto VARCHAR(12) NOT NULL,
    nombre_proyecto VARCHAR(255) NOT NULL,
    descripcion TEXT,
    conac VARCHAR(1),
    id_programa INT, 
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    anio VARCHAR(4),
    CONSTRAINT FK_programa FOREIGN KEY (id_programa) REFERENCES programas_presupuestarios(id_programa) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS dependencias;
CREATE TABLE dependencias(
    id_dependencia INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_dependencia VARCHAR(255) NOT NULL,
    nivel VARCHAR(50),
    id_dependencia_gen INT,
    id_director INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    active INT,
    anio VARCHAR(4),
    CONSTRAINT FK_dependencia_general FOREIGN KEY (id_dependencia_gen) REFERENCES dependencias_generales(id_dependencia) ON DELETE CASCADE,
    CONSTRAINT FK_director FOREIGN KEY (id_director) REFERENCES titulares(id_titular) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS areas;
CREATE TABLE areas(
    id_area INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_area VARCHAR(255) NOT NULL,
    id_dependencia INT,
    id_dependencia_general INT,
    id_dependencia_aux INT,
    id_proyecto INT,
    id_titular INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    anio VARCHAR(4),
    active INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



-- Permisos:
-- 1 > Maxima autoridad (gobierno Digital y Gobierno por resultados)
-- 2 > validacion de avances, agregar actividades e indicadores, validar reconducciones y mas
-- 3 > Presidente municipal. Permite ver estadisticas de cada area, no puede editar.
-- 4 > Director o coordinador de dependencia, puede agrar avances, evidencia, pedir reconducciones y CREAR USUARIOS. @metepec.
-- 5 > Enlace. Permite capturar avances, pedir reconducciones, solo administra su propia cuenta.
DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios(
    id_usuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255),
    apellidos VARCHAR(255),
    id_permiso INT NOT NULL,
    correo_electronico VARCHAR(255),
    tel VARCHAR(255),
    contrasena VARCHAR(255),
    id_dependencia INT,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_registro INT,
    CONSTRAINT fk_usuarios_usuarios FOREIGN KEY (id_registro) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO usuarios (nombre, apellidos, id_permiso, correo_electronico, tel, contrasena) VALUES('German', 'Guillen', 1, 'goder@live.com', '7224531128', '123456');


DROP TABLE IF EXISTS usuarios_eliminados;
CREATE TABLE usuarios_eliminados(
    id_usuario_eliminado INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_anterior INT,
    nombre VARCHAR(255),
    apellidos VARCHAR(255),
    id_permiso INT NOT NULL,
    correo_electronico VARCHAR(255),
    tel VARCHAR(255),
    contrasena VARCHAR(255),
    id_dependencia INT,
    fecha_creacion DATETIME,
    fecha_eliminacion DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_registro INT,
    id_eliminante INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS permisos;
CREATE TABLE permisos(
    id_permiso INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS actividades;
CREATE TABLE actividades(
    id_actividad INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    codigo_actividad VARCHAR(2) NOT NULL,
    nombre_actividad VARCHAR(500) NOT NULL,
    unidad VARCHAR(255) NOT NULL, 
    id_unidad INT,
    programado_anual_anterior VARCHAR(50),
    alcanzado_anual_anterior VARCHAR(50),
    id_area INT,
    id_validacion INT,
    validado INT,
    enero INT,
    febrero INT,
    marzo INT,
    abril INT,
    mayo INT,
    junio INT,
    julio INT,
    agosto INT,
    septiembre INT,
    octubre INT,
    noviembre INT,
    diciembre INT,
    creacion DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_creacion INT,
    modificacion DATETIME, 
    id_modifiacion INT,
    CONSTRAINT FK_area FOREIGN KEY (id_area) REFERENCES areas(id_area) ON DELETE CASCADE,
    CONSTRAINT FK_id_validacion FOREIGN KEY (id_validacion) REFERENCES usuarios (id_usuario) ON DELETE CASCADE,
    CONSTRAINT FK_id_creacion FOREIGN KEY (id_creacion) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS avances;
CREATE TABLE avances(
    id_avance INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    mes VARCHAR(2),
    avance VARCHAR(25),
    justificacion TEXT,
    path_evidenia VARCHAR(255),
    path_evidenia_evidencia VARCHAR(255),
    descripcion_evidencia TEXT,
    id_actividad INT,
    id_usuario_avance INT,
    validado INT DEFAULT 0,
    id_usuario_validador INT,
    fecha_avance TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_validador TIMESTAMP NULL,
    CONSTRAINT FK_avane_actividad FOREIGN KEY (id_actividad) REFERENCES actividades (id_actividad) ON DELETE CASCADE,
    CONSTRAINT FK_user_captura FOREIGN KEY (id_usuario_avance) REFERENCES usuarios (id_usuario) ON DELETE CASCADE,
    CONSTRAINT FK_user_valida FOREIGN KEY (id_usuario_validador) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS indicadores;
CREATE TABLE indicadores(
    id_indicador INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_indicador TEXT,
    variable_a TEXT,
    variable_b TEXT,
    variable_c TEXT,
    nivel_indicador ENUM('NF', 'NP', 'NC', 'NA'),
    sub_nivel VARCHAR(3),
    resumen VARCHAR(255),
    nombre VARCHAR(255),
    formula TEXT,
    frecuencia VARCHAR(10),
    tipo VARCHAR(50),
    medios_verificacion VARCHAR(255),
    supuestos VARCHAR(255),
    id_programa_presupuestario INT,
    CONSTRAINT FK_indicador_programa FOREIGN KEY (id_programa_presupuestario) REFERENCES programas_presupuestarios(id_programa) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS indicadores_uso;
CREATE TABLE indicadores_uso(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    anio VARCHAR(4),
    id_dep_general INT,
    id_dep_aux INT,
    id_proyecto INT,
    variable_a VARCHAR(255),
    variable_b VARCHAR(255),
    variable_c VARCHAR(255),
    tipo_op_a VARCHAR(255),
    tipo_op_b VARCHAR(255),
    tipo_op_c VARCHAR(255), 
    umedida_a VARCHAR(255),
    umedida_b VARCHAR(255),
    umedida_c VARCHAR(255), 
    interpretacion TEXT,
    tipo VARCHAR(255),
    formula VARCHAR(50),
    dimension VARCHAR(50),
    periodicidad VARCHAR(20), -- mensual, trimestral, semetral y anual
    factor_de_comparacion VARCHAR(255),
    desc_factor_de_comparacion VARCHAR(255),
    linea_base VARCHAR(255),
    medios_de_verificacion VARCHAR(255),
    at1 VARCHAR(10),
    at2 VARCHAR(10),
    at3 VARCHAR(10),
    at4 VARCHAR(10),
    bt1 VARCHAR(10),
    bt2 VARCHAR(10),
    bt3 VARCHAR(10),
    bt4 VARCHAR(10),
    ct1 VARCHAR(10),
    ct2 VARCHAR(10),
    ct3 VARCHAR(10),
    ct4 VARCHAR(10),
    id_dependencia INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    id_alta INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS avances_indicadores;
CREATE TABLE avances_indicadores(
    id_avance INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    trimestre VARCHAR(1),
    avance_a VARCHAR(25),
    avance_b VARCHAR(25),
    avance_c VARCHAR(25),
    justificacion TEXT,
    path_evidenia VARCHAR(255),
    path_evidenia_evidencia VARCHAR(255),
    descripcion_evidencia VARCHAR(255),
    id_indicador INT,
    id_usuario_reporta INT,
    reportado INT,
    validado INT DEFAULT 0,
    id_usuario_valida INT,
    fecha_reporta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_valida TIMESTAMP NULL,
    year VARCHAR(4)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;



DROP TABLE IF EXISTS descripcion_programas; 
CREATE TABLE descripcion_programas(
    id_descripcion INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    foda_fortalezas TEXT,
    foda_oportunidades TEXT,
    foda_debilidades TEXT,
    foda_amenazas TEXT,
    estrategia_programa TEXT,
    objetivo_pdm TEXT,
    estrategia_pdm TEXT,
    linea_pdm TEXT,
    objetivos_ods TEXT,
    metas_ods TEXT,
    id_area INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_descripcion_programa_area FOREIGN KEY (id_area) REFERENCES areas(id_area) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS comments; 
CREATE TABLE comments( 
    id_comment INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_usuario INT,
    comment TEXT,
    id_actividad INT,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS reconducciones_atividades; 
CREATE TABLE reconducciones_atividades(
    id_reconduccion_actividades INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_area INT,
    no_oficio VARCHAR(15),
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP(),
    dep_general VARCHAR(255),
    dep_aux VARCHAR(255),
    programa VARCHAR(255),
    validado INT DEFAULT 0,
    id_solicitante INT,
    id_validador INT,
    fecha_validacion DATETIME
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS programacion_reconducciones; 
CREATE TABLE programacion_reconducciones(
    id_programaciones_reconduccion INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id_reconduccion INT NOT NULL,
    tipo ENUM("interna", "externa"),
    no_actividad VARCHAR(2),
    id_actividad INT,
    desc_actividad VARCHAR(255),
    u_medida VARCHAR(255),
    meta_anual_anterior VARCHAR(255),
    meta_anual_actual VARCHAR(255),
    act_realizadas_sofar VARCHAR(255),
    programacion_inicial VARCHAR(255),
    programacion_final VARCHAR(255),
    justificacion TEXT,
    txt_creacion TEXT,
    txt_cancelacion TEXT 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS reconducciones_indicadores; 
CREATE TABLE reconducciones_indicadores(
    id_reconduccion_indicadores INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    no_oficio VARCHAR(15),
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP(),
    tipo_movimiento ENUM("Cancelación-Reconducción","Creación-Incremento"),
    dep_general VARCHAR(10),
    dep_aux VARCHAR(10),
    programa_p VARCHAR(6),
    objetivo TEXT,
    proyecto VARCHAR(12),
    proyecto_name VARCHAR(255),
    niv_mir VARCHAR(10),
    nombre_indicador TEXT,
    variables_indicador TEXT,
    unidad_medida VARCHAR(255),
    tipos_operacion VARCHAR(255),
    programacion_inicial VARCHAR(255),
    avance VARCHAR(255),
    programacion_modificada VARCHAR(255),
    calendario_trimestral TEXT,
    justificacion_impacto TEXT,
    id_dependencia INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS unidades_medida; 
CREATE TABLE unidades_medida(
    id_unidad INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_unidad VARCHAR(255) NOT NULL,
    descripcion_unidad TEXT,
    id_registro INT,
    last_edit INT,
    fecha_alta DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO unidades_medida (id_registro, nombre_unidad, descripcion_unidad) VALUES
(1,"Abeja","Insecto que vive en colonias y produce miel y cera."),
(1,"Acción","Hecho o efecto de hacer, como acto que da constancia a la realización de una actividad notable o de gran relevancia."),
(1,"Acta","Certificación en que constan los hechos más notables de la vida de una persona. \nDa constancia de hechos, acuerdos y decisiones tomadas. \nRelación escrita de lo sucedido o acordado en una junta. \nDocumento legal extendido por un juez. \nDefinir en este apartado Acta de audiencia, la Dependencia usuaria deberá definir este concepto (Contraloría)."),
(1,"Acto de Fiscalización","Acciones que se realizan para generar presencia fiscal permanente y sistemática en los distintos sectores que conforman el entorno económico, para lograr una mayor recaudación y generar el cumplimiento de las obligaciones tributarias."),
(1,"Actuación","Cada una de las actividades que se desarrollan dentro de los procesos instaurados ante los tribunales."),
(1,"Actualización","Poner al día datos, normas, precios, rentas, salarios, entre otros.(RAE)."),
(1,"Acuerdo","Decisión tomada en común por dos o más personas, para llevar a cabo un compromiso que se adquiere, derivado de resoluciones tomadas en reuniones con una autoridad, con uno o algunos de sus inmediatos colaboradores o subalternos o con organizaciones sociales y privadas. \nDeterminación proveniente de un acto jurídico tomada en común por dos o más personas, para llevar a cabo un compromiso."),
(1,"Acuerdo de inicio de procedimiento","Definir por la Dependencia usuaria: Contraloría"),
(1,"Adecuación","Adaptar algo a las necesidades o condiciones de una persona o de una cosa.(RAE)."),
(1,"Adolescente","Todo individuo en un rango de 10 a 19 años en el que se inicia la fase del desarrollo psicofisiológico, en la transición de la infancia a la adultez."),
(1,"Adulto","Persona que ha llegado a su mayor desarrollo; legalmente se le considera a partir de los 18 años de edad. \nEn salud, se considera adulto a las personas a partir de los 20 años hasta antes de los 60.(Para los fines del catálogo de unidad de medida incluye a los adultos mayores, considerados dentro del grupo etario de 60 años y más)."),
(1,"Agente","Persona autorizada oficialmente para ejecutar operaciones de seguridad."),
(1,"Agroempresa","Unidad económica de producción agropecuaria."),
(1,"Agrupación","Conjunto de individuos que se reúnen para llevar a cabo diversas actividades."),
(1,"Albergue","Establecimiento que otorga servicios y apoyos asistenciales a personas en condiciones de vulnerabilidad a fin de promover su integración social y productiva sin establecer una dependencia institucional permanente."),
(1,"Alcantarilla","Obra de canalización y desagüe de desperdicios líquidos y agua de lluvia."),
(1,"Almacén","Depósito en el que se guardan mercancías de diversa naturaleza."),
(1,"Alumno","Discípulo respecto de su maestro, de la materia que aprende o de la escuela donde estudia. \nEs la persona inscrita en cualquier grado de los diversos niveles y modalidades del sistema educativo estatal."),
(1,"Ambulancia","Vehículo de auxilio para transportar heridos o enfermos."),
(1,"Amparo","Garantía constitucional para asegurar la libertad, el goce de los derechos y la correcta aplicación de una ley o de un reglamento administrativo."),
(1,"Análisis","Determinación de las propiedades físicas, químicas y biológicas del agua, suelo y productos naturales y elaborados; como de muestras que la población deja en laboratorios, todo ello para conocer el estado de salud de las personas, la calidad física del medio natural y la sanidad de los productos. \nExamen y estudio detallado de un proyecto específico para conocer sus elementos, características, estructura e impacto, con la finalidad de evaluar su viabilidad."),
(1,"Animal","Ser orgánico que vive y se mueve por el propio impulso."),
(1,"Anteproyecto","Elaboración de trabajos preliminares para llevar a cabo el proyecto principal o definitivo."),
(1,"Anticonceptivo","Instrumento u objeto que ayuda a impedir la fecundación o concepción."),
(1,"Año","Período de doce meses, a contar desde el día 1 de enero hasta el 31 de diciembre, equivale a 365 días, salvo el año bisiesto."),
(1,"Aparato (funcional)","Conjunto de instrumentos, objetos, órganos o piezas organizados para cumplir con una función determinada."),
(1,"Apelación","Pedir al juez o tribunal superior que revoque una sentencia."),
(1,"Apiario","Conjunto de colmenas destinadas a la producción de miel."),
(1,"Aplicación","Programa preparado para una utilización específica (Informática).(RAE)."),
(1,"Apoyo","Favorecer, patrocinar, ayudar.(RAE)."),
(1,"Árbol","Organismo vegetal con tronco leñoso que se ramifica a mayor o menor altura del suelo."),
(1,"Archivo","Concentración de documentos debidamente ordenados y seleccionados. \nTambién se refiere al conjunto de documentos que integran el expediente de la terminación o conclusión definitiva de Juicios."),
(1,"Archivo digital","Conjunto de datos almacenados en la memoria de una computadora u otro dispositivo electrónico que puede manejarse con una instrucción única."),
(1,"Arcina","Estibamiento de forrajes de forma piramidal."),
(1,"Área Geográfica","Superficie territorial que identifica a una o más localidades."),
(1,"Arqueo ","Análisis de los movimientos realizados de efectivo en un tiempo determinado. \nConsiste en comprobar que todos los movimientos se han contabilizado y que el dinero que se encuentra registrado concuerda con el dinero físico de la caja.(Arqueo de caja)."),
(1,"Artesanía","Producto elaborado manualmente con materia prima natural."),
(1,"Artículo","Escrito de cierta extensión de un periódico, revista o publicación periódica. \nUnidad de cuantificación unitaria. \nApartado que señala un mandamiento jurídico o normativo."),
(1,"Asamblea","Reunión de integrantes de comunidades, productores, instituciones o individuos en general, para tomar acuerdos sobre asuntos de su interés."),
(1,"Asesoría","Orientación y apoyo en la toma de decisiones o en la resolución de actividades. \nBrindar apoyo a personas o grupos sociales para atender, tramitar y resolver procedimientos."),
(1,"Asistencia","Conjunto de personas que están presentes en un acto.(RAE)."),
(1,"Asociación","Conjunto de personas que se agrupan para alcanzar un objetivo común y donde cada uno posee los mismos derechos y obligaciones."),
(1,"Aspirante","Persona que pretende un empleo, distinción, título, entre otros.(RAE)."),
(1,"Atlas","Colección de mapas geográficos."),
(1,"Atleta","Persona físicamente capacitada con aptitudes para realizar un deporte."),
(1,"Audiencia","Evento en el que una autoridad recibe a personas para resolver asuntos. \nExposición de argumentos y pruebas ante los tribunales."),
(1,"Auditoría","Proceso sistemático, para obtener, analizar, verificar y evaluar de manera objetiva, las evidencias relacionadas con los informes de las actividades económicas y de la gestión de las dependencias, entidades públicas, órganos autónomos de los ayuntamientos, con el fin de determinar el grado de correspondencia del contenido informativo, con las evidencias que le dieron origen, así como determinar si se han aplicado las normas jurídicas administrativas y los principios establecidos."),
(1,"Auditorio","Edificio en el que se realizan eventos."),
(1,"Aula","Salón o sala donde se imparten clases."),
(1,"Autobús","Vehículo automotor de transporte colectivo."),
(1,"Autorización","Acto de una autoridad por el cual se permite a alguien una actuación.(RAE)."),
(1,"Avalúo","Estimación del valor monetario de un bien mueble o inmueble. \n\nPara los bienes inmuebles consiste en la aplicación de Tablas de Valores Unitarios de Suelo y Construcciones aprobadas por la H. \n\nLegislatura del Estado de México para la obtención del valor catastral y/o el valor comercial del inmueble de acuerdo a la normatividad vigente en la materia."),
(1,"Ave","Animal vertebrado ovíparo de respiración pulmonar, cuerpo cubierto de plumas, con dos patas y dos alas, que en su mayoría son aptas para el vuelo."),
(1,"Averiguación","Iniciación y determinación de la situación jurídica de los actos para ejercer acción penal."),
(1,"Aviso","Indicio, señal.(RAE)."),
(1,"Ayuntamiento","Organización gubernamental representada por un Presidente Municipal, sus Síndicos y Regidores, que encabeza a un municipio, y es el responsable de atender los servicios públicos de la población que se asienta en su territorio."),
(1,"Barrido manual","Limpiar un lugar arrastrando la suciedad con algo como una escoba.(RAE)."),
(1,"Base","Definir por la Dependencia usuaria, Contraloría "),
(1,"Base de Datos","Conjunto de datos que pertenecen al mismo contexto, almacenados sistemáticamente para su uso, en la actualidad la mayoría de las bases de datos o banco de datos tienen ya un formato electrónico que permite mejorar la problemática al almacenar, procesar y consultar datos."),
(1,"Bazar","Tienda (espacio) en que se venden productos muy variados.(RAE)."),
(1,"Beca","Apoyo o estímulo que se otorga en forma económica, en especie o en exención, para promover y coadyuvar a la formación educativa, cultural, deportiva, técnica y profesional de los individuos en la entidad."),
(1,"Beneficiario","Persona que disfruta de un goce o un beneficio."),
(1,"Biblioteca","Lugar que concentra para su consulta, información bibliográfica o hemerográfica."),
(1,"Bitácora","Libro pequeño o conjunto de papel en que se lleva la cuenta y razón, o en que se escriben algunas noticias, ordenanzas o instrucciones.(RAE)."),
(1,"Bodega","Espacio cerrado utilizado para guardar objetos de diversa índole."),
(1,"Boletín","Documento que tiene el propósito de difundir información referente a programas, proyectos o actividades realizadas por las dependencias y entidades públicas."),
(1,"Bordo","Área acondicionada para almacenar agua, para épocas de estiaje o para riego u otro uso."),
(1,"Brigada","Conjunto de personas especializadas para solucionar fenómenos determinados."),
(1,"Cabeza","Unidad de medida en los diversos hatos ganaderos."),
(1,"Cadete","Persona capacitada en instituciones académicas policiales con fines educativos formativos para integrarse a los cuerpos de policía."),
(1,"Caja de Captación","Construcción de un sistema de captación de agua de lluvia, que se utiliza en áreas urbanas/rurales."),
(1,"Calificación","Puntuación obtenida en un examen o en cualquier tipo de prueba.(RAE)"),
(1,"Calle","Vía pública, habitualmente asfaltada o empedrada, entre edificios o solares.(RAE)"),
(1,"Campamento","Instalación provisional para el desarrollo de actividades específicas."),
(1,"Campaña","Conjunto de actos o esfuerzos de índole diversa que se aplican a conseguir un fin determinado.(RAE)."),
(1,"Canasta Alimentaria","Es el conjunto de alimentos y/o productos de higiene y aseo personal, diseñado para las personas con pobreza multidimensional o alimentaria."),
(1,"Cancha","Espacio físico destinado a realizar actividades deportivas."),
(1,"Capacitación","Es el conjunto de acciones de preparación que desarrollan las entidades laborales, dirigidas a mejorar las competencias, calificaciones y recalificaciones para cumplir con calidad las funciones del puesto de trabajo y alcanzar los máximos resultados productivos o de servicio. \n\nEste conjunto de acciones permite crear, mantener y elevar los conocimientos, habilidades y actitudes de los trabajadores para asegurar su desempeño exitoso."),
(1,"Cápsula informativa","Información que se transmite a través de medios de comunicación radiofónicos y televisivos, para conocimiento público."),
(1,"Cárcamo","Depósito utilizado para el almacenamiento de agua."),
(1,"Carpeta","Documentación entregada como respaldo para la realización de una obra, informe o denuncia."),
(1,"Carril","En una vía pública, cada banda longitudinal destinada al tránsito de una sola fila de vehículos."),
(1,"Carta de aceptación","Definir por la Dependencia usuaria: Educación, Cultura y Bienestar Social"),
(1,"Carta de liberación","Definir por la Dependencia usuaria: Educación, Cultura y Bienestar Social"),
(1,"Carta Geográfica","Representación territorial que incluye datos generales sobre los principales asentamientos humanos, elementos hidrológicos, vías de comunicación, infraestructura y equipamiento urbano, áreas naturales protegidas, zonas urbanas, división municipal y principales elevaciones (curvas de nivel)."),
(1,"Cartel","Papel impreso o manuscrito que se coloca en un lugar visible o público, con el objeto de dar a conocer información."),
(1,"Cartilla","Ficha de identificación personal que contiene datos específicos."),
(1,"Cartografía","Trazado y estudio de mapas geográficos"),
(1,"Caseta","Edificación que sirve para la admisión de personas u objetos (se refiere a casetas de vigilancia)."),
(1,"Caso","Problema que se plantea manifestando la particularidad que contiene."),
(1,"Catálogo","Documento que contiene información en forma jerárquica y sistemática."),
(1,"Cédula","Documento que hace constar cualquier información."),
(1,"Celebración","Realizar un acto festivo por algo que lo merece.(RAE)."),
(1,"Censo","Padrón de personas o bienes que contiene diversas variables socioeconómicas."),
(1,"Ceremonia","Evento público oficial que se realiza para conmemorar festividades, aniversarios, reconocimientos, premiaciones y graduaciones educativas."),
(1,"Certamen","Concurso literario, artístico o científico."),
(1,"Certificación","Dicho de una autoridad competente. \n\nHacer constar por escrito una realidad de hecho.(RAE)"),
(1,"Certificado","Documento que acredita la validez oficial de actos, actividades o estudios."),
(1,"Chaleco","Protector corporal a prueba de balas."),
(1,"Cirugía","Intervención quirúrgica efectuada a humanos o animales.(Esterilizaciones)"),
(1,"Citatorio","Documento con que se convoca a una persona para que comparezca ante alguien."),
(1,"Club","Asociación voluntaria de miembros con objetivos comunes."),
(1,"Código","Conjunto de normas legales sistemáticas que regulan unitariamente una materia determinada.(RAE)."),
(1,"Colonia","Conjunto de personas que viven en un espacio geográfico específico."),
(1,"Colono","Habitante de una colonia."),
(1,"Comisión","Conjunto de individuos elegidos por una asamblea para encargarse de asuntos específicos. \n\nFacultad que se da a una persona para que ejecute un encargo."),
(1,"Comité","Estructura formal integrada por personas capacitadas para deliberar, decidir y ejecutar sobre materias, o discutir asuntos de interés público. \n\nAgrupación de personas elegidas en una asamblea, las cuales tienen la encomienda de representar y negociar determinados asuntos."),
(1,"Compendio","Recopilación de datos de una misma materia.");
INSERT INTO unidades_medida (id_registro, nombre_unidad, descripcion_unidad) VALUES
(1,"Compromiso","Obligación contraída sobre el cumplimiento de una solicitud, referente a una acción, proyecto u obra, que realiza el ejecutivo del gobierno municipal, proveniente de la petición de la ciudadanía."),
(1,"Comunicado","Nota, declaración o información que se da a conocer a través de medios de comunicación impresos o por audio."),
(1,"Comunidad","Grupo específico de personas, que a menudo viven en una zona geográfica definida, comparten la misma cultura, valores y normas, organizadas en una estructura social de acuerdo al tipo de relaciones que la comunidad ha desarrollado a lo largo del tiempo."),
(1,"Concierto","Evento organizado para promover manifestaciones artísticas musicales."),
(1,"Conciliación","Acto de comparecencia de las partes litigantes en asuntos de diverso carácter, ante la presencia de un juez para lograr un acuerdo."),
(1,"Concursante","Candidato a pruebas de distinta índole para obtener un premio o reconocimiento."),
(1,"Concurso","Procedimiento administrativo que tiene como finalidad, elegir la propuesta que ofrezca mayores ventajas para ejecutar una obra o prestar un servicio."),
(1,"Condón","Preservativo, o funda fina y elástica usada a fin de evitar la fecundación o el posible contagio de enfermedades de transmisión sexual."),
(1,"Conferencia","Exposición de uno o más especialistas sobre un tema específico ante una audiencia."),
(1,"Conflicto","Problema o desacuerdo suscitado por una o más personas, alterando el orden social o territorial."),
(1,"Congreso","Asamblea de personas para deliberar sobre asuntos o actividades específicas."),
(1,"Consejo","Estructura colegiada que tiene como propósito la discusión y análisis de determinado asunto."),
(1,"Consignación","Entrega de detenidos a las autoridades competentes."),
(1,"Constancia","Documento que se expide a solicitud de parte, para certificar o confirmar un hecho."),
(1,"Consulta","Revisión médica otorgada a personas que así lo soliciten para determinar su estado de salud. \n\nManifestación de orientación de la población."),
(1,"Consultorio","Unidad médica donde se atiende al público o se dan consultas médicas."),
(1,"Contrato","Documento normativo que regula las relaciones laborales o comerciales, delegando derechos y obligaciones para las partes que intervienen."),
(1,"Contribuyente","Persona física o moral a quien se le imponen ciertas obligaciones de pago, a cambio de la prestación de determinados servicios y poder sostener de esta manera el gasto público."),
(1,"Controversia","Opiniones contrapuestas entre dos o más personas, a fin de dar solución a conflictos suscitados de la población usuaria de un bien o servicio."),
(1,"Convenio","Pacto entre dos o más instituciones, personas o asociaciones por el que ambas partes aceptan derechos y obligaciones, pudiendo ser éste proveniente de un acto judicial. \n\nActo para la realización conjunta de programas."),
(1,"Convenio en liquidación","Definir por la Dependencia usuaria: Tesorería"),
(1,"Convocatoria","Documento en el que se invita a participar en eventos o concursos."),
(1,"Cooperativa","Organización cuyo objetivo es beneficiar a productores o consumidores."),
(1,"Cría","Primera etapa vital de un organismo de cualquier especie."),
(1,"Criadero","Lugar destinado para el resguardo de animales durante su crianza."),
(1,"Cuarto","Parte de un inmueble donde habitan las personas."),
(1,"Cuestionario","Lista de preguntas que se proponen con cualquier fin.(RAE)."),
(1,"Curso","Conjunto de reuniones donde se imparten pláticas o talleres para transmitir conocimientos a la población o servidores públicos."),
(1,"Declaración","Documento a través del cual los servidores públicos municipales presentan información relacionada con su patrimonio e intereses."),
(1,"Defensa","Exposición de los argumentos con que se defiende a alguien."),
(1,"Delegación","Área de trabajo separada de la matriz que se encuentra en una localidad específica. \n\nTerritorialmente la Delegación Municipal, es una circunscripción que nace del acuerdo facultativo del Ayuntamiento, dividiendo al Territorio del Municipio en una o más Delegaciones."),
(1,"Delito","Quebrantamiento de la ley, acción u omisión voluntaria, castigada por la ley con pena grave."),
(1,"Demanda","Procedimiento jurídico para el cual se busca la impartición de justicia."),
(1,"Denuncia","Queja realizada ante alguna instancia del gobierno por personas en general."),
(1,"Dependencia","Unidad Administrativa del Poder Ejecutivo Municipal que presta un bien o servicio."),
(1,"Deportista","Persona que practica alguna disciplina deportiva."),
(1,"Desayuno","Porción alimenticia del día que se proporciona a la población escolar de educación básica, con el fin de coadyuvar en el mejoramiento de su estado de nutrición."),
(1,"Desfile","Marchar en orden y formación.(RAE)."),
(1,"Día","Tiempo de duración de la rotación de la tierra sobre sí misma."),
(1,"Diagnóstico","Análisis sobre una situación, entorno, realidad, problema o fenómeno."),
(1,"Diagrama","Representación gráfica de un hecho o sistema cualquiera, por medio de símbolos."),
(1,"Dictamen","Resolución emitida por autoridades oficiales u opinión que se forma sobre una cosa o asunto."),
(1,"Difusión","Propagar o divulgar conocimientos, noticias, actitudes, costumbres, modas, entre otros.(RAE)."),
(1,"Diligencia","Actos procesales realizados por los actuarios, en cumplimiento a las resoluciones y acuerdos dictados por el Juez."),
(1,"Diplomado","Nivel de estudios de especialización para la superación profesional."),
(1,"Director","Persona que realiza la planeación, programación, coordinación y evaluación de las tareas para el funcionamiento de las Dependencias de conformidad con el marco jurídico y administrativo aplicable."),
(1,"Directorio","Lista de los archivos, ficheros o programas almacenados en la memoria de un ordenador o en cualquier otro medio."),
(1,"Disco","Dispositivo de memoria de gran capacidad integrado en la computadora o en otro dispositivo electrónico, o conectado a ellos.(RAE). \n\nObjeto en el cual los grupos artísticos musicales graban su música."),
(1,"Diseño","Boceto, formato, dummie o material a imprimir o muestra de impresión."),
(1,"Dispositivo de seguridad","Estrategia de un conjunto de elementos, orientada al logro de algún fin."),
(1,"Distribución","Dividir algo entre varias personas, designando lo que a cada una corresponde, según voluntad, conveniencia, regla o derecho.(RAE)."),
(1,"Docente","Persona dedicada a proporcionar y facilitar conocimientos a los estudiantes en cualquier nivel educativo o materia."),
(1,"Documento","Es el testimonio material de un hecho o acto realizado en el ejercicio de las funciones por instituciones o personas físicas, jurídicas, públicas o privadas, registrado en una unidad de información en cualquier tipo de soporte incluyendo soporte escrito. \n\nEscrito en que constan datos fidedignos o susceptibles de ser empleados como tales para probar algo.(RAE)."),
(1,"Donación","Liberalidad de alguien que transmite gratuitamente algo que le pertenece a favor de otra persona que lo acepta."),
(1,"Donativo","Regalo o dádiva que se da a determinada población o comunidad."),
(1,"Ecotecnia","Instrumento desarrollado para aprovechar eficientemente los recursos naturales y materiales."),
(1,"Edificio","Bien inmueble de carácter público o privado."),
(1,"Egresado","Sujeto que ha aprobado como alumno todos los cursos y actividades que conforman un plan de estudios, quedando en condiciones de obtener un certificado o en su caso un grado académico con su proceso de titulación correspondiente."),
(1,"Ejemplar","Cada uno de los escritos impresos sacados de un original."),
(1,"Elaboración","Transformar una cosa u obtener un producto por medio de un trabajo adecuado.(RAE)."),
(1,"Elección","Designación, que regularmente se hace por votos, para algún cargo, comisión, entre otros.(RAE)."),
(1,"Elemento","Parte constitutiva o integrante de algo.(RAE)"),
(1,"Emergencia","Situación de peligro o desastre que requiere una acción inmediata.(RAE)."),
(1,"Empleado","Persona que labora o presta sus servicios generales o profesionales en empresas públicas o privadas."),
(1,"Empleo","Ocupar a alguien, encargándole un negocio, comisión o puesto. \n\nOcupación de mano de obra en actividades productivas mediante remuneración."),
(1,"Empresa","Unidad económica de producción o distribución de bienes o servicios."),
(1,"Empresario","Persona que dirige cualquier tipo de empresa."),
(1,"Encuesta","Técnica de investigación utilizada para obtener información cuantitativa y cualitativa verbal o escrita a un grupo de personas o instituciones por medio de cuestionarios."),
(1,"Entrevista","Técnica de obtención de información, mediante una conversación de naturaleza profesional entre dos o más individuos para una investigación determinada, por lo que las preguntas y respuestas son espontáneas y flexibles."),
(1,"Equipamiento","Proveer del equipo necesario a industrias, urbanizaciones, sanatorios u otros establecimientos.(RAE)."),
(1,"Equipo","Conjunto de personas. \nColección de utensilios, instrumentos y aparatos especiales para un fin determinado.(RAE)."),
(1,"Equipo de cómputo","Equipo para el procesamiento de la información y realización de tareas informáticas, tales como, computadoras, impresoras, entre otros."),
(1,"Escritura","Documento que otorga el título de propiedad."),
(1,"Escuela","Inmueble o establecimiento con la infraestructura necesaria donde se imparte la enseñanza al alumnado de un mismo tipo, nivel o servicio, sin importar el turno."),
(1,"Espaciomapa","Documento de carácter cartográfico que resulta de la fusión digital de una imagen de satélite y una de tipo pancromático."),
(1,"Establecimiento","Espacio físico ocupado por un inmueble, principalmente de carácter comercial o fabril."),
(1,"Estancia","Espacio físico para la permanencia de menores, jóvenes y adultos para proporcionar ayuda de diversos tipos, como: educación, actividades recreativas, de custodia, entre otras."),
(1,"Estanque","Receptáculo de agua construido para proveer el riego, criar peces o servir de abrevadero."),
(1,"Estímulo","Agente físico, químico, mecánico, económico, entre otros, que desencadena una reacción funcional en un organismo o persona.(RAE)."),
(1,"Estudiante","Persona que se caracteriza por su vinculación con el aprendizaje y por la búsqueda de nuevos conocimientos en diversas materias o actividades mediante los sistemas escolarizado, no escolarizado y/o abierto."),
(1,"Estudio","Análisis sujeto a variables que permitan conocer sobre una materia, es también una investigación profunda y racional para conocer la situación que guarda un objeto en particular y proponer la solución óptima para el mismo."),
(1,"Evaluación","Proceso administrativo por medio del cual se lleva a cabo la comparación de avance o cumplimiento de la programación de los recursos y metas respecto de los planes y programas, para medir el resultado real de las operaciones durante su ejecución; que identifique los orígenes, causas y efectos de las desviaciones, para la adopción de medidas correctivas o bien confirmar las estrategias y programas operativos, y de esta manera alimentar el proceso corrigiendo la planeación o la ejecución."),
(1,"Evento","Suceso importante, organizado y programado de índole pública, que permite la promoción de un bien o servicio, intercambio de experiencias o el cumplimiento de una atribución gubernamental."),
(1,"Examen","Prueba a la que se somete el candidato a un grado o empleo. \nInstrumento utilizado para identificar el grado de conocimiento que tiene una persona o la calidad con la que se realizaron diferentes acciones. \nAdemás se refiere al diagnóstico sobre la salud de las personas."),
(1,"Excursión","Paseo o viaje corto a sitios determinados por turismo, estudio o investigación."),
(1,"Exhorto","Comunicación de un juez o tribunal a otro de la misma categoría, para la práctica de alguna diligencia judicial."),
(1,"Expediente","Conjunto de documentos o datos escritos y/o digitales correspondientes a un asunto, negocio o procedimiento administrativo."),
(1,"Exposición","Montaje que se hace de artículos diversos en lugares estratégicos para darlos a conocer a la ciudadanía o a los interesados en la materia."),
(1,"Extintor","Aparato utilizado para la extinción de incendios."),
(1,"Faena","Trabajo corporal. \nQuehacer.(RAE)."),
(1,"Familia","Núcleo básico de la sociedad."),
(1,"Feria","Concurrencia de gente en un evento para acceder a determinados programas públicos."),
(1,"Festival","Acto público artístico y/o cultural."),
(1,"Fianza","Cantidad de dinero o bien material que se entrega como garantía del cumplimiento de una obligación.(RAE)."),
(1,"Fiscalización","Mecanismo de control para obtener recursos tributarios."),
(1,"Folleto","Publicación impresa con temas informativos (propaganda)."),
(1,"Foro","Reunión de personas competentes en determinada materia, que debaten ciertos asuntos ante un auditorio que a veces interviene en la discusión.(RAE)."),
(1,"Fosa séptica","Pozo usado como sanitario en zonas sin servicios de agua potable y drenaje"),
(1,"Fuga","Salida accidental o por avería de los sistemas de conducción o almacenamiento de fluidos."),
(1,"Fumigación","Acción de desinfectar o eliminar plagas por medio de polvos en suspensión, vapores, líquidos, gases o humo."),
(1,"Gaceta","Nombre del diario oficial del Gobierno.(RAE)."),
(1,"Galería","Espacio donde se exponen colecciones de obras artísticas.");
INSERT INTO unidades_medida (id_registro, nombre_unidad, descripcion_unidad) VALUES
(1,"Gestión","Hacer diligencias para resolver o conseguir un beneficio colectivo determinado."),
(1,"Gimnasio","Establecimiento destinado a la práctica de ejercicios físicos."),
(1,"Grabación","Registro de sonidos en un medio magnético."),
(1,"Granja","Espacio específico creado para cultivo intensivo de diversas especies semovientes."),
(1,"Grupo","Conjunto de personas que se reúnen por intereses comunes."),
(1,"Guía Técnica","Documento administrativo que proporciona a los servidores públicos, lineamientos, criterios y recomendaciones básicas para facilitarles el cumplimiento de determinadas actividades que les han sido encomendadas, sean éstas de naturaleza administrativa o jurídica. \nExiste otra modalidad dirigida a los usuarios para facilitarles el cumplimiento de sus obligaciones o ejercicio de sus derechos vinculados con alguna autoridad pública."),
(1,"Hectárea","Medida de superficie equivalente a diez mil metros cuadrados."),
(1,"Herramienta","Utensilio de trabajo que apoya o facilita la labor."),
(1,"Huerto","Terreno destinado al cultivo de legumbres y árboles frutales."),
(1,"Impreso","Libro, folleto u hoja que se ha obtenido por una impresora."),
(1,"Incendio","Fuego que se propaga, causando estragos."),
(1,"Indicador","Es una expresión cuantitativa y/o cualitativa que dimensiona la magnitud o grado de cumplimiento de un objetivo. \nEs el resultado de un algoritmo o fórmula de cálculo que se compara con una meta establecida; permite observar los cambios vinculados con la ejecución del programa en el tiempo."),
(1,"Informe","Descripción oral o escrita de las características y circunstancias de un suceso o asunto."),
(1,"Ingreso","Flujo o entrada de dinero asignado."),
(1,"Inmueble","Bien material que por su naturaleza no puede ser trasladado."),
(1,"Inspección","Acción de revisión del cumplimiento de la normatividad establecida en un lugar determinado, examen físico de la aplicación de los recursos, documentos u obras, con el objeto de cerciorarse de su existencia y cumplimiento bajo la norma o mandato establecido."),
(1,"Institución educativa","Conjunto de profesores y alumnos de una misma enseñanza.(RAE)."),
(1,"Instructor","Persona responsable de capacitar al personal."),
(1,"Inventario","Es una recopilación de todos los activos de la entidad con su amortización aplicada si procede, fecha de adquisición y valor contable."),
(1,"Investigación","Realizar actividades intelectuales y experimentales de modo sistemático con el propósito de aumentar los conocimientos sobre una determinada materia.(RAE)."),
(1,"Jaula","Espacio delimitado con cualquier tipo de malla para albergar especies de semovientes y acuícolas, pudiendo ser fijas, transportables, flotantes o sumergibles."),
(1,"Jornada","Reunión o congreso, normalmente de un tema específico y de corta duración.(RAE)."),
(1,"Joven","Persona con características y requerimientos propios determinados por la edad."),
(1,"Juicio","Procedimiento para la aplicación judicial del derecho, a petición y en ejercicio de un derecho legalmente instituido para resolver sobre una cuestión pública."),
(1,"Kilogramo","Unidad de medida de peso que equivale a 1000 gramos."),
(1,"Kilómetro","Unidad de medida para superficies, equivalente a 1000 metros lineales."),
(1,"KM 2","Superficie territorial de 1 millón de metros cuadrados."),
(1,"Lámpara","Aparato para generar o irradiar luz artificial."),
(1,"Laudo","Fallo emitido por un tribunal de arbitraje a fin de dar resolución pronta y expedita a una demanda laboral, con apego al marco jurídico"),
(1,"Lechería","Local en el que se distribuyen productos lácteos."),
(1,"Letrina","Lugar destinado para evacuar los excrementos."),
(1,"Levantamiento","Estudio técnico y descriptivo de un terreno, examinando la superficie terrestre en la cual se tienen en cuenta las características físicas, geográficas y geológicas del terreno, pero también sus variaciones y alteraciones.(Topográfico)."),
(1,"Libro","Conjunto de hojas de papel impresas en un volumen encuadernado."),
(1,"Licencia","Permiso oficial otorgado a particulares para conducir vehículo automotor o realizar de forma oficial una acción o actividad comercial. \nIncluye tambien el concepto de Licencias para uso de suelo: Autorización del uso del suelo bajo las disposiciones normativas para el aprovechamiento de los inmuebles ubicados en el territorio municipal.(Actividades permitidas en cada predio)."),
(1,"Licitación","Procedimiento legal para que una institución pública pueda adjudicar la contratación de obras y servicios a determinado proveedor."),
(1,"Litro","Unidad de medida de capacidad que equivale a un decímetro cúbico."),
(1,"Llamada","Comunicación telefónica para resolver u orientar las demandas sociales."),
(1,"Localidad","Espacio territorial que aglutina núcleos de población y puede ser urbana y rural."),
(1,"Luminaria","Lámpara utilizada para la instalación del alumbrado público."),
(1,"Manifestación","Documento mediante el cual los servidores públicos rinden un informe de sus valores, bienes y adeudos, sea por anualidad o por alta y baja en el servicio."),
(1,"Mantenimiento","Conjunto de operaciones y cuidados necesarios para que instalaciones, edificios, industrias, entre otros, puedan seguir funcionando adecuadamente.(RAE)."),
(1,"Manual","Documento que contiene información explícita, ordenada y sistemática sobre la organización y procedimientos administrativos, para la orientación o ejercicio de un proceso."),
(1,"Mapa","Representación simplificada de la realidad, con proyección cartográfica, con simbología y a escala que representa una porción del territorio."),
(1,"Médico ","Persona que ejerce la medicina con los grados académicos necesarios que lo facultan para ello."),
(1,"Mercado ","Espacio físico (inmueble) o virtual para la venta y compra de mercancías y servicios."),
(1,"Mes ","Agrupación de medida del tiempo que representa una doceava parte en que se divide un año."),
(1,"Metro ","Unidad fundamental de longitud."),
(1,"Metro 2","Unidad de medida utilizada para cuantificar y medir superficie equivalente a un cuadrado de un metro por lado."),
(1,"Metro 3","Unidad de medida de volumen."),
(1,"Miles de metros cúbicos ","Unidad fundamental de volumen utilizada para medir líquidos."),
(1,"Miles de metros cúbicos por segundo ","Unidad fundamental de volumen utilizada para medir líquidos en espacio de tiempo."),
(1,"Minuta ","Referencia de acciones y acuerdos relevantes que se realizaron en una reunión de trabajo o asamblea."),
(1,"Mobiliario ","Bienes muebles que facilitan la ejecución de las actividades."),
(1,"Módulo","Local o establecimiento colocado estratégicamente para prestar servicios de auxilio e información. \nDivisiones de un todo documental que marcan estructura lógica para la consecusión de un fin determinado."),
(1,"Molino ","Máquina para moler, artefacto con que se quebranta o machaca alguna cosa."),
(1,"Monitoreo ","Revisión y análisis periódico o permanente de actividades, eventos, fenómenos y hechos."),
(1,"Monumento ","Obra pública construida en memoria de una acción heroica u otro hecho singular del devenir histórico del Municipio."),
(1,"Mujer ","Persona del sexo femenino."),
(1,"Museo","Lugar en que se guardan los objetos de las ciencias o las artes para su conservación, exposición y/o estudio."),
(1,"Niño/a","Persona del género masculino/femenino en la etapa de vida desde el nacimiento hasta la pubertad; en materia de salud está diferenciado por la edad de los 0 a 9 años."),
(1,"Nómina","Lista de personas que van a percibir un salario por su fuerza de trabajo intelectual o física."),
(1,"Notaría","Oficina donde se gestiona el registro, se avala o da fe pública de actos, patrimonios, acuerdos, convenios y certifica documentos legales."),
(1,"Notificación","Acción de informar sobre algún asunto, caso, evento o padecimiento."),
(1,"Obra","Trabajo de construcción, equipamiento, conservación o remodelación de infraestructura."),
(1,"Obra artística","Expresa contenidos didácticos, ideas y opiniones."),
(1,"Oficina","Espacio de trabajo, generalmente en un inmueble."),
(1,"Operativo","Acciones de revisión o supervisión de carácter legal usualmente sorpresivas."),
(1,"Ordenamiento","Conjunto de leyes o normas relativas a una misma materia."),
(1,"Organigrama","Sinopsis o esquema de la organización de una entidad, de una empresa o de una tarea.(RAE)."),
(1,"Organismo","Conjunto de oficinas, dependencias y personas que forman un cuerpo institucional de carácter público, privado o social."),
(1,"Organización","Asociación de individuos constituida para un determinado fin."),
(1,"Ortofoto","Producto resultante de la corrección geométrica de fotografías verticales, obtenidas mediante fotografía aérea de un área territorial determinada, que ofrece una representación fiel y detallada del terreno."),
(1,"Paciente","Beneficiario directo de la atención médica y hospitalaria con el fin de promover, proteger y restaurar su salud."),
(1,"Padrón","Censo de personas, instituciones, negocios, empresas, entre otros, según el fin que persiga."),
(1,"Página web","Localización de determinada información a consultar, mediante la red de internet."),
(1,"Parcela","Superficie pequeña que resulta de la división de un terreno."),
(1,"Parque","Área con fines recreativos o industriales, entre otros."),
(1,"Participante","Persona que interviene o tiene parte en alguna cosa."),
(1,"Patronato","Organización cuyo objetivo es reunir fondos para fines no lucrativos."),
(1,"Patrulla","Unidad vehicular oficial encargada de la vigilancia y seguridad pública."),
(1,"Pensión","Cantidad de dinero entregada periódicamente a alguien."),
(1,"Peritaje ","Informe elaborado por un perito, de acuerdo a los requerimientos procesales."),
(1,"Perito","Persona autorizada para dar opinión acerca de una cuestión de tipo legal."),
(1,"Permiso","Licencia o consentimiento para hacer o ejecutar una obra o acción por un tiempo establecido."),
(1,"Persona","Unidad de género humano que particulariza socialmente a los individuos."),
(1,"Peso"," Fuerza con que la Tierra atrae a un cuerpo.(RAE)"),
(1,"Pesos","Unidad monetaria de México.(RAE)"),
(1,"Petición","Solicitud verbal o escrita mediante la cual la población metepequense pide a las instancias gubernamentales municipales un bien, servicio u otra cosa."),
(1,"Pieza","Unidad para contabilizar objetos en general."),
(1,"Placa","Superficie utilizada para hacer inscripciones. \nLámina de identificación vehicular."),
(1,"Plan","Modelo sistemático de una actuación, que se elabora anticipadamente para dirigirla y encauzarla que contiene en forma ordenada y coherente, en tiempo y espacio; diagnóstico, objetivos, estrategias, políticas, metas, directrices y tácticas, así como los medios y acciones que se utilizarán para llegar a los fines deseados."),
(1,"Plano","Representación gráfica de una porción del territorio, que considera la curvatura de la tierra."),
(1,"Planta de tratamiento","Infraestructura utilizada para dar tratamiento a las aguas residuales de origen industrial y doméstico."),
(1,"Plantación","Sembradío de diferentes especies de plantas."),
(1,"Plantilla ","Relación ordenada por categorías de las dependencias y empleados del servicio público."),
(1,"Plática","Reunión de expertos que debaten sobre un tema o el intercambio de opiniones en el marco de una conferencia. \nPueden tratar sobre cualquier tema."),
(1,"Plaza ","Es el cargo a donde se asigna el personal. \nLugar físico de una población."),
(1,"Población","Conjunto de personas que habitan la tierra o cualquier división geográfica de ella."),
(1,"Porcentaje","Parte proporcional de una unidad, tanto por ciento.");
INSERT INTO unidades_medida (id_registro, nombre_unidad, descripcion_unidad) VALUES
(1,"Poste","Pilar instalado básicamente para la dotación de algún servicio."),
(1,"Pozo","Agujero profundo que se hace en la tierra para diversos fines."),
(1,"Práctica","Método utilizado para realizar ensayos o trabajos que permitan generar conocimiento o, el desempeño de actividades o acciones."),
(1,"Practicante","Persona encargada de desempeñar una determinada actividad de manera temporal y bajo supervisión, para completar la currícula académica."),
(1,"Pre gira","Reunión previa de planeación y coordinación para la realización de un evento."),
(1,"Predio","Espacio de terreno utilizado para construcción de instalaciones."),
(1,"Premio ","Recompensa, galardón o remuneración que se da por algún mérito o servicio.(RAE)."),
(1,"Prestación","Beneficio adicional al sueldo integrado mensual que se otorga a los servidores públicos, derivado de convenios con sus representaciones sindicales. \nPuede hacerse extensiva a los servidores públicos no sindicalizados, de acuerdo a la normatividad establecida."),
(1,"Presupuesto","Estimación financiera anticipada de los egresos e ingresos, para cumplir con metas, objetivos y programas establecidos, documento financiero que tiene el carácter de ley."),
(1,"Procedimiento ","Método o sistema estructurado para ejecutar algunas acciones; actuación por trámites judiciales, administrativos o médicos."),
(1,"Proceso","Conjunto ordenado de etapas o fases de un fenómeno en evolución con características de acción concatenada, dinámica y progresiva, que concluye con la obtención de un resultado determinado."),
(1,"Producto","Cosa fabricada natural o artificialmente; también puede considerarse como el resultado de un trabajo u operación."),
(1,"Productor","Persona dedicada al proceso de creación de bienes de consumo y satisfactores."),
(1,"Profesor","Personal que imparte conocimientos acerca de alguna materia, o que se dedica a la docencia."),
(1,"Promedio","Término medio o suma de varias cantidades, dividida por el número de ellas."),
(1,"Promoción","Conjunto de actividades cuyo objetivo es dar a conocer algo.(RAE)."),
(1,"Promotor","Persona encargada de la organización, promoción y difusión de las actividades."),
(1,"Propuesta","Proposición o idea que se manifiesta y ofrece a alguien para un fin.(RAE)."),
(1,"Protocolo","Regla ceremonial establecida por decreto o costumbre. \nSserie ordenada de escrituras, matrices y otros documentos que un notario público autoriza y custodia con ciertas formalidades."),
(1,"Proveedor","Persona que suministra lo necesario para lograr un fin."),
(1,"Proyecto","Documento que concreta objetivos municipales y/o sectoriales y define una acción o acciones a realizar orientadas al logro de objetivos específicos con metas medibles o de infraestructura, incluye aquellas actividades encaminadas para el fortalecimiento del Sector Público, como son: cursos, talleres, asesorías, consultorías, tutorías, reconocimientos, planes, programas, modelos, entre otros. \norientados a la solución de un problema, mediante la aplicación de recursos y una metodología determinada."),
(1,"Publicación","Escrito o contenido divulgado a través de diversos medios para hacerlo de conocimiento general."),
(1,"Puente ","Construcción específica que permite comunicar dos espacios."),
(1,"Queja","Denuncia o inconformidad presentada ante autoridades por abusos de poder o influencia en los servicios prestados."),
(1,"Ración","Porción alimenticia que se distribuye."),
(1,"Radio","Equipo de comunicación central para transmitir información."),
(1,"Reclutado","Integrante de una corporación policíaca oficial."),
(1,"Recomendación","Resultado del análisis de un mandamiento jurídico o normativo."),
(1,"Reconocimiento","Acción y efecto de analizar los mecanismos que intervienen en un sistema. \nExpresión satisfactoria relativa a la realización de un trámite, prestación de un servicio o del desempeño de un servidor público o de la población en general en el desarrollo de alguna actividad. \nEl reconocimiento puede ser con algún estímulo ya sea económico o en especie."),
(1,"Recurso","Medio de impugnación que pueden hacer valer los particulares afectados en contra de actos y resoluciones de carácter administrativo y jurídico que determinen las autoridades."),
(1,"Red","Sistema de ordenadores conectados entre sí por medio de la telecomunicación."),
(1,"Región","Área territorial con características específicas y homogéneas."),
(1,"Registro","Inscribir un dato determinado o bien. \nInstancia donde se lleva a cabo la inscripción de dichos datos."),
(1,"Reglamento","Ordenamiento administrativo para organizar y normar las funciones públicas."),
(1,"Relleno sanitario","Depósito de desechos sólidos."),
(1,"Remodelación","Cambio que permite una mejor estética y funcionalidad de los inmuebles."),
(1,"Reparación","Arreglo de equipo e infraestructura."),
(1,"Reporte","Información que se transmite de forma periódica con calidad y oportunidad para que quien la solicita pueda tomar decisiones en relación al estado en que se encuentra el ejercicio de una acción y/o la prestación de un bien o servicio."),
(1,"Requerimiento","Avisar o hacer saber a través de una autoridad pública, ya sea administrativa, judicial o fiscal, de la presentación o pago de obligaciones"),
(1,"Rescate","Evento donde se pone a salvo a una persona y generalmente se ofrece atención médica a través de un grupo organizado."),
(1,"Residente","Dentro del ámbito ámbito geográfico a aquellas personas que en la fecha de referencia tienen establecida su residencia habitual en el mismo. \nMédico que radica temporal o permanentemente en donde presta sus servicios."),
(1,"Resolución","Decreto, providencia, auto o fallo de autoridad gubernamental o judicial. \nDocumento a través del cual se da a conocer la determinación de una autoridad administrativa o jurisdiccional, respecto de un asunto en particular."),
(1,"Reunión","Unir, juntar o congregar a personas para el planteamiento, análisis y resolución de acuerdos comunes."),
(1,"Revista","Publicación periódica que contiene una variedad de artículos sobre un tema determinado."),
(1,"Rodal","Espacio pequeño de terreno que se utiliza para la creación de invernaderos."),
(1,"Ruta","Camino e itinerario para realizar un recorrido y brindar un servicio público."),
(1,"Santuario","Área natural protegida, cuerpo de agua o bosque y su zona de influencia."),
(1,"Seguro","Contrato que obliga a resarcir pérdidas o daños que ocurran."),
(1,"Semáforo","Poste indicador que regula el tráfico vehicular a través de señales viales."),
(1,"Semana","Período de tiempo integrado por siete días."),
(1,"Seminario","Reunión para realizar trabajos de investigación o práctica de alguna disciplina o temática específica."),
(1,"Sentencia","Dictamen o parecer que se emite sobre el proceder de una persona o asignación de una función, procedimiento, bien o servicio."),
(1,"Señal","Placa o anuncio en vías de comunicación para indicar algo."),
(1,"Servicio","Prestación humana que satisface alguna necesidad individual o social y que no consisten en la producción de bienes materiales."),
(1,"Servicio Electrónico","Trámites y servicios que se hacen a través del uso de las tecnologías de información y telecomunicaciones."),
(1,"Servicio Funerario","Comprende las acciones que se realizan para ofrecer servicios de velación, cremación y ataúdes."),
(1,"Servidor Público","Persona física que presta a una institución pública, empresas de participación municipal, sociedades o asociaciones asimiladas a estas, en los fideicomisos públicos y en los órganos autónomos un trabajo personal subordinado de carácter material o intelectual o de ambos géneros, mediante el pago de un sueldo."),
(1,"Sesión","Reunión con integrantes de instituciones públicas, privadas, asociaciones civiles y organismos gubernamentales, donde se tratan temas comunes. \nTambién puede considerarse la atención terapéutica y psicoterapeuta individual o familiar."),
(1,"Silo","Depósito de forrajes para la alimentación de animales o almacenamiento de granos."),
(1,"Simposio","Conferencia o reunión donde se tratan diferentes temas."),
(1,"Simulacro","Ensayo o práctica que se realiza para asegurar una mejor respuesta en casos de incendios, desastres o siniestros."),
(1,"Siniestro","Situación imprevista que origina daños o pérdidas en las personas."),
(1,"Sistema","Estructura funcional compuesta de organismos, principios y normas. \nSe refiere también a sistemas informáticos, los cuales son un conjunto de procesos y/o programas que permiten la ejecución de varias tareas de forma concurrente; dichos sistemas son utilizados para agilizar las actividades laborales de cualquier individuo o dependencia pública."),
(1,"Sitio web","Es un conjunto de páginas web, comunes a un dominio de Internet o subdominio en la World Wide Web (www). \nA las páginas de un sitio web se accede desde una dirección raíz común (URL) llamada portada, que normalmente reside en el mismo servidor físico."),
(1,"Sociedad","Entidad creada por la ley, facultad para adquirir activos, incurrir en obligaciones y dedicarse a determinadas actividades. \nSe conforma por dos o más socios que adquieren diferentes grados de responsabilidad ante terceros, dependiendo de la forma jurídica que revista la entidad."),
(1,"Solicitante","Persona que requiere de información que prestan las entidades públicas municipales."),
(1,"Solicitud","Requerimiento que realiza una persona o instancia a otra, por medio de un documento formal."),
(1,"Supervisión","Comprende las acciones de vigilancia, coordinación y ejecución de actividades y obras, de tal manera que éstas se realicen de acuerdo a lo programado y de manera satisfactoria."),
(1,"Supervisor","Es la autoridad que, en el ámbito de su responsabilidad, vigila el cumplimiento de las disposiciones normativas y técnicas aplicables; apoya y asesora para facilitar y promover la calidad de la administración pública municipal; favorece la comunicación y realiza las demás funciones que sean necesarias para la debida operación de los programas, el buen desempeño y el cumplimiento de los fines de las políticas públicas."),
(1,"Taller","Área de trabajo con características especiales para actividades manuales o de enseñanza. \nTambién se considera a las reuniones de trabajo donde obtienen aprendizajes prácticos, se forman desarrollan y perfeccionan hábitos, habilidades y capacidades."),
(1,"Tarjeta Comedores Comunitarios","Definir por la Dependencia usuaria: Desarrollo Social / Evaluar si la unidad de medida puede ser Credencial."),
(1,"Tarjeta el Privilegio de Ser Joven","Definir por la Dependencia usuaria: Desarrollo Social / Evaluar si la unidad de medida puede ser Credencial."),
(1,"Tarjeta Médico en tu Casa","Definir por la Dependencia usuaria: Salud / Evaluar si la unidad de medida puede ser Credencial."),
(1,"Tarjetas Programa CASAFF","Definir por la Dependencia usuaria: Desarrollo Social / Evaluar si la unidad de medida puede ser Credencial."),
(1,"Terapia","Tratamiento aplicado a pacientes para su rehabilitación."),
(1,"Testificación","Verificación de actos legales u otros que se celebran en las instituciones, dependencias, entidades y ayuntamientos."),
(1,"Título electrónico","Estructura de datos del título profesional, diploma de especialidad y grado académico, que permite a la autoridad educativa autenticar la información contenida en el documento académico generado por las instituciones educativas de educación media superior y superior."),
(1,"Toma","Conexión a la instalación de la red general de agua potable."),
(1,"Tonelada","Unidad de peso equivalente a 1000 kg."),
(1,"Torneo","Desarrollo de concursos o eventos donde por eliminación queda un ganador."),
(1,"Tractor","Vehículo agrícola utilizado para el cultivo."),
(1,"Trámite","Procedimientos que se tienen que realizar para la solicitud de un bien o servicio ante la instancia de gobierno muinicipal, y de la cual debe de obtenerse una respuesta."),
(1,"Trámite simplificado","Procedimiento que realiza la población, cuya respuesta es ágil y se da en una sola ventanilla."),
(1,"Transformador","Dispositivo electromagnético que permite aumentar o disminuir el voltaje y la intensidad de una corriente alterna, de forma tal que el flujo de su producto permanezca constante."),
(1,"Transmisión","Acción y efecto de transmitir información por medios electrónicos."),
(1,"Tratamiento","Acción que se realiza para mejorar el estado o situación de una persona, de un bien o de información, según corresponda."),
(1,"Tríptico","Documento que contiene información, distribuida en tres páginas unidas, de modo que puedan doblarse las laterales sobre la del centro."),
(1,"Unidad","Se entiende por uno, (unidad de medida). \nSingularidad numérica o en lo cualitativo. \nIdentificación de inmueble para su uso habitual."),
(1,"Unidad recolectora","Definir por la Dependencia usuaria: Servicios Públicos");


DROP TABLE IF EXISTS unidades_medida_eliminadas; 
CREATE TABLE unidades_medida_eliminadas(
    id_unidad_eliminada INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre_unidad VARCHAR(255) NOT NULL,
    descripcion_unidad TEXT,
    id_registro INT,
    last_edit INT,
    fecha_alta DATETIME,
    id_elimina INT,
    fecha_elimina DATETIME DEFAULT CURRENT_TIMESTAMP()
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


DROP TABLE IF EXISTS setings;
CREATE TABLE setings(
    id_setings INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    year_report VARCHAR(4) NOT NULL,
    id_tesoreria INT,
    id_uippe INT,
    anteproyectoFechas VARCHAR(13),
    proyectoFechas VARCHAR(13),
    programaAFechas VARCHAR(13)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO setings (year_report, anteproyectoFechas, proyectoFechas, programaAFechas) VALUES ("2022", "01,01;01,01", "01,01;01,01", "01,01;01,01");